## 服务器配置
server:
  port: 8080

## Vita 配置
project:
  # 是否开启登陆验证码
  captcha-open: false
  shrio:
    # cookie记住登录信息时间，默认7天（天）
    remember-me-timeout: 7
    # Session会话超时时间，默认30分钟（秒）
    global-session-timeout: 1800
  upload:
    # file-path: E:/PersonalWork/Zero2One/Github/Zero2One/Wonderful_Code/Vita/upload
    static-path: /upload/**

## spring配置
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vita?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    data-username: root
    data-password: root

  # jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: com.agu.common.dialect.MySQLDialectUTF8
      hibernate.format_sql: false
    open-in-view: true

  # thymeleaf 模板设置
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # json 配置
  jackson:
    time-zone: Asia/Shanghai